// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vänskap_Api.Data;

#nullable disable

namespace Vänskap_Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260521133455_InitPostgres")]
    partial class InitPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Vänskap_Api.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("About")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("InterestId")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastProfilePictureUpload")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("ProfilePicturePath")
                        .HasColumnType("text");

                    b.Property<int>("ProfilePictureUploadCountToday")
                        .HasColumnType("integer");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("InterestId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Vänskap_Api.Models.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EventId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("Vänskap_Api.Models.ConversationParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConversationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("UserId");

                    b.ToTable("ConversationParticipants");
                });

            modelBuilder.Entity("Vänskap_Api.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgeRangeMax")
                        .HasColumnType("integer");

                    b.Property<int?>("AgeRangeMin")
                        .HasColumnType("integer");

                    b.Property<int>("ConversationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ImageUpdateCountToday")
                        .HasColumnType("integer");

                    b.Property<string>("Img")
                        .HasColumnType("text");

                    b.Property<int?>("InterestId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastImageUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("InterestId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Vänskap_Api.Models.EventInterest", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<int>("InterestId")
                        .HasColumnType("integer");

                    b.HasKey("EventId", "InterestId");

                    b.HasIndex("InterestId");

                    b.ToTable("EventInterest");
                });

            modelBuilder.Entity("Vänskap_Api.Models.EventParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("EventParticipants");
                });

            modelBuilder.Entity("Vänskap_Api.Models.FriendRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReceiverId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("FriendRequests");
                });

            modelBuilder.Entity("Vänskap_Api.Models.Friendship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FriendId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("FriendId");

                    b.HasIndex("UserId");

                    b.ToTable("Friendships");
                });

            modelBuilder.Entity("Vänskap_Api.Models.Interest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cooking"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Travel"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Photography"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Fitness"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Running"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Hiking"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Cycling"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Swimming"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Yoga"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Music"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Dance"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Painting"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Drawing"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Writing"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Reading Books"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Playing Guitar"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Playing Piano"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Programming"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Gardening"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Fishing"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Hunting"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Baking"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Fashion"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Interior Design"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Movies"
                        },
                        new
                        {
                            Id = 26,
                            Name = "TV Series"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Podcasts"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Cars"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Motorcycles"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Animals"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Dogs"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Cats"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Volunteering"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Stocks"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Investing"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Economics"
                        },
                        new
                        {
                            Id = 37,
                            Name = "History"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Psychology"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Philosophy"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Astronomy"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Science"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Politics"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Environmental Issues"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Debate"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Self-Development"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Meditation"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Mindfulness"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Skiing"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Snowboarding"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Sailing"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Surfing"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Golf"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Football"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Basketball"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Tennis"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Padel"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Baseball"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Esports"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Board Games"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Chess"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Card Games"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Role-Playing Games"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Camping"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Road Trips"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Backpacking"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Languages"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Culture"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Food Culture"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Brewing Beer"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Wine Tasting"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Cocktails"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Coffee"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Technology"
                        },
                        new
                        {
                            Id = 74,
                            Name = "AI"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Game Development"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Web Development"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Mobile Apps"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Entrepreneurship"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Startups"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Social Media"
                        },
                        new
                        {
                            Id = 82,
                            Name = "YouTube"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Streaming"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Stand-up Comedy"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Improvisation"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Acting"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Theatre"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Art"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Museums"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Architecture"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Fashion Photography"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Vintage"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Antiques"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Flea Markets"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Minimalism"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Zero Waste"
                        },
                        new
                        {
                            Id = 97,
                            Name = "DIY Projects"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Woodworking"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Ceramics"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Origami"
                        });
                });

            modelBuilder.Entity("Vänskap_Api.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ConversationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Vänskap_Api.Models.MessageReadAt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MessageId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("UserId");

                    b.ToTable("MessageReadAt");
                });

            modelBuilder.Entity("Vänskap_Api.Models.UserInterest", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int>("InterestId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "InterestId");

                    b.HasIndex("InterestId");

                    b.ToTable("UserInterest");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Vänskap_Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Vänskap_Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vänskap_Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Vänskap_Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vänskap_Api.Models.ApplicationUser", b =>
                {
                    b.HasOne("Vänskap_Api.Models.Interest", null)
                        .WithMany("Users")
                        .HasForeignKey("InterestId");
                });

            modelBuilder.Entity("Vänskap_Api.Models.Conversation", b =>
                {
                    b.HasOne("Vänskap_Api.Models.Event", "Event")
                        .WithOne("Conversation")
                        .HasForeignKey("Vänskap_Api.Models.Conversation", "EventId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Vänskap_Api.Models.ConversationParticipant", b =>
                {
                    b.HasOne("Vänskap_Api.Models.Conversation", "Conversation")
                        .WithMany("ConversationParticipants")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vänskap_Api.Models.ApplicationUser", "User")
                        .WithMany("ConversationParticipations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vänskap_Api.Models.Event", b =>
                {
                    b.HasOne("Vänskap_Api.Models.ApplicationUser", "CreatedByUser")
                        .WithMany("CreatedEvents")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vänskap_Api.Models.Interest", null)
                        .WithMany("Events")
                        .HasForeignKey("InterestId");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Vänskap_Api.Models.EventInterest", b =>
                {
                    b.HasOne("Vänskap_Api.Models.Event", "Event")
                        .WithMany("EventInterests")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vänskap_Api.Models.Interest", "Interest")
                        .WithMany()
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Interest");
                });

            modelBuilder.Entity("Vänskap_Api.Models.EventParticipant", b =>
                {
                    b.HasOne("Vänskap_Api.Models.Event", "Event")
                        .WithMany("EventParticipants")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vänskap_Api.Models.ApplicationUser", "User")
                        .WithMany("EventParticipations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vänskap_Api.Models.FriendRequest", b =>
                {
                    b.HasOne("Vänskap_Api.Models.ApplicationUser", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vänskap_Api.Models.ApplicationUser", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Vänskap_Api.Models.Friendship", b =>
                {
                    b.HasOne("Vänskap_Api.Models.ApplicationUser", null)
                        .WithMany("Friendships")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("Vänskap_Api.Models.ApplicationUser", "Friend")
                        .WithMany()
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vänskap_Api.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Friend");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vänskap_Api.Models.Message", b =>
                {
                    b.HasOne("Vänskap_Api.Models.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vänskap_Api.Models.ApplicationUser", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Vänskap_Api.Models.MessageReadAt", b =>
                {
                    b.HasOne("Vänskap_Api.Models.Message", "Message")
                        .WithMany("ReadAts")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vänskap_Api.Models.ApplicationUser", "User")
                        .WithMany("ReadMessages")
                        .HasForeignKey("UserId");

                    b.Navigation("Message");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vänskap_Api.Models.UserInterest", b =>
                {
                    b.HasOne("Vänskap_Api.Models.Interest", "Interest")
                        .WithMany()
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vänskap_Api.Models.ApplicationUser", "User")
                        .WithMany("UserInterests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vänskap_Api.Models.ApplicationUser", b =>
                {
                    b.Navigation("ConversationParticipations");

                    b.Navigation("CreatedEvents");

                    b.Navigation("EventParticipations");

                    b.Navigation("Friendships");

                    b.Navigation("ReadMessages");

                    b.Navigation("UserInterests");
                });

            modelBuilder.Entity("Vänskap_Api.Models.Conversation", b =>
                {
                    b.Navigation("ConversationParticipants");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Vänskap_Api.Models.Event", b =>
                {
                    b.Navigation("Conversation")
                        .IsRequired();

                    b.Navigation("EventInterests");

                    b.Navigation("EventParticipants");
                });

            modelBuilder.Entity("Vänskap_Api.Models.Interest", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Vänskap_Api.Models.Message", b =>
                {
                    b.Navigation("ReadAts");
                });
#pragma warning restore 612, 618
        }
    }
}
